import type { PlayId, VendorEntry } from '../types';

/**
 * `present`-tier detection: one row per vendor, one generic matcher walks them all (see core).
 * Adding a vendor is adding a row. Don't ration rows; breadth is the whole point of this tier.
 *
 * `scriptUrlPatterns` are case-insensitive substrings matched against request URLs; they stream
 * as requests arrive. `globalNames` are the fallback, visible only at settle. Prefer patterns.
 *
 * These fingerprints are seeded from public knowledge of each vendor's CDN, NOT from the step-0
 * probe (which hasn't landed). Vendors rename and re-host: when a site known to run a vendor
 * comes back empty, suspect this list before the site, and reconcile against probe fixtures.
 */

const CART: PlayId = 'cart_recovery';
const OVE: PlayId = 'order_value_expansion';
const RETARGET: PlayId = 'retargeting_suppression';
const CHURN: PlayId = 'churn_winback';
const PROSPECT: PlayId = 'intelligent_prospecting';
const ALL_PLAYS: PlayId[] = [CART, OVE, RETARGET, CHURN, PROSPECT];

export const vendorTable: VendorEntry[] = [
	// ESP / SMS: the build's actual gap; lifecycle messaging is what BlueConic sells.
	{
		id: 'cart.esp.klaviyo',
		vendor: 'klaviyo',
		category: 'esp',
		play: [CART, CHURN],
		scriptUrlPatterns: [
			'static.klaviyo.com',
			'static-tracking.klaviyo.com',
			'a.klaviyo.com',
			'klaviyo.js',
		],
		globalNames: ['klaviyo', '_learnq'],
	},
	{
		id: 'cart.sms.attentive',
		vendor: 'attentive',
		category: 'sms',
		play: [CART, CHURN],
		scriptUrlPatterns: ['cdn.attn.tv', 'attentivemobile.com'],
		globalNames: ['__attentive'],
	},
	{
		id: 'cart.sms.postscript',
		vendor: 'postscript',
		category: 'sms',
		play: [CART, CHURN],
		scriptUrlPatterns: ['sdk.postscript.io', 'postscript.io'],
		globalNames: ['postscript', 'Postscript'],
	},
	{
		id: 'cart.esp.listrak',
		vendor: 'listrak',
		category: 'esp',
		play: [CART, CHURN],
		scriptUrlPatterns: ['cdn.listrakbi.com', 'listrak.com', 's.listrak'],
		globalNames: ['_ltk'],
	},
	{
		id: 'cart.esp.bluecore',
		vendor: 'bluecore',
		category: 'esp',
		play: [CART, CHURN],
		scriptUrlPatterns: ['bluecore.com', 'ee.bluecore.com'],
		globalNames: ['bluecore'],
	},
	{
		id: 'cart.esp.braze',
		vendor: 'braze',
		category: 'esp',
		play: [CART, CHURN],
		scriptUrlPatterns: ['sdk.braze.com', 'sdk.iad-01.braze.com', 'appboy'],
		globalNames: ['braze', 'appboy'],
	},
	{
		id: 'cart.esp.iterable',
		vendor: 'iterable',
		category: 'esp',
		play: [CART, CHURN],
		scriptUrlPatterns: ['links.iterable.com', 'iterable.com'],
		globalNames: [],
	},
	{
		id: 'cart.esp.omnisend',
		vendor: 'omnisend',
		category: 'esp',
		play: [CART, CHURN],
		scriptUrlPatterns: ['omnisend.com', 'omnisrc.com'],
		globalNames: ['omnisend'],
	},
	{
		id: 'cart.esp.sendlane',
		vendor: 'sendlane',
		category: 'esp',
		play: [CART, CHURN],
		scriptUrlPatterns: ['sendlane.com'],
		globalNames: [],
	},
	{
		id: 'cart.esp.mailchimp',
		vendor: 'mailchimp',
		category: 'esp',
		play: [CART, CHURN],
		scriptUrlPatterns: ['chimpstatic.com', 'list-manage.com', 'mailchimp.com'],
		globalNames: ['mailchimp'],
	},
	{
		id: 'cart.esp.drip',
		vendor: 'drip',
		category: 'esp',
		play: [CART, CHURN],
		scriptUrlPatterns: ['tag.getdrip.com', 'getdrip.com'],
		globalNames: ['_dcq', '_dcs'],
	},

	// Exit-intent / on-site capture: the on-site recovery story.
	{
		id: 'cart.exit_intent.justuno',
		vendor: 'justuno',
		category: 'exit_intent',
		play: [CART],
		scriptUrlPatterns: ['cdn.justuno.com', 'justuno.com'],
		globalNames: ['juapp', 'ju_num'],
	},
	{
		id: 'cart.exit_intent.optimonk',
		vendor: 'optimonk',
		category: 'exit_intent',
		play: [CART],
		scriptUrlPatterns: ['onsite.optimonk.com', 'optimonk.com'],
		globalNames: ['OptiMonk'],
	},
	{
		id: 'cart.exit_intent.privy',
		vendor: 'privy',
		category: 'exit_intent',
		play: [CART],
		scriptUrlPatterns: ['widget.privy.com', 'privy.com'],
		globalNames: ['Privy'],
	},
	{
		id: 'cart.exit_intent.wunderkind',
		vendor: 'wunderkind',
		category: 'exit_intent',
		play: [CART],
		scriptUrlPatterns: [
			'bounceexchange.com',
			'api.bounceexchange.com',
			'wunderkind.co',
		],
		globalNames: ['bouncex'],
	},
	{
		id: 'cart.exit_intent.sleeknote',
		vendor: 'sleeknote',
		category: 'exit_intent',
		play: [CART],
		scriptUrlPatterns: ['sleeknotecustomerscripts.com', 'sleeknote.com'],
		globalNames: [],
	},
	{
		id: 'cart.exit_intent.privyer_sumo',
		vendor: 'sumo',
		category: 'exit_intent',
		play: [CART],
		scriptUrlPatterns: ['load.sumo.com', 'sumo.com'],
		globalNames: ['Sumo'],
	},
	{
		id: 'cart.exit_intent.wisepops',
		vendor: 'wisepops',
		category: 'exit_intent',
		play: [CART],
		scriptUrlPatterns: ['wisepops.com', 'loader.wisepops.com'],
		globalNames: ['wisepops'],
	},

	// Ad pixels: Retargeting Suppression, and the count IS the demo visual.
	{
		id: 'ads.pixel.meta',
		vendor: 'meta',
		category: 'ad_pixel',
		play: [RETARGET],
		scriptUrlPatterns: ['connect.facebook.net', 'facebook.com/tr'],
		globalNames: ['fbq', '_fbq'],
	},
	{
		id: 'ads.pixel.tiktok',
		vendor: 'tiktok',
		category: 'ad_pixel',
		play: [RETARGET],
		scriptUrlPatterns: ['analytics.tiktok.com', 'tiktok.com/i18n/pixel'],
		globalNames: ['ttq'],
	},
	{
		id: 'ads.pixel.google_ads',
		vendor: 'google_ads',
		category: 'ad_pixel',
		play: [RETARGET],
		scriptUrlPatterns: [
			'googleadservices.com',
			'googleads.g.doubleclick.net',
			'google.com/pagead',
		],
		globalNames: ['google_trackConversion'],
	},
	{
		id: 'ads.pixel.ga4',
		vendor: 'ga4',
		category: 'ad_pixel',
		play: [RETARGET],
		scriptUrlPatterns: [
			'google-analytics.com/g/collect',
			'analytics.google.com/g/collect',
			'googletagmanager.com/gtag/js',
		],
		globalNames: ['gtag', 'dataLayer'],
	},
	{
		id: 'ads.pixel.gtm',
		vendor: 'google_tag_manager',
		category: 'ad_pixel',
		play: [RETARGET],
		scriptUrlPatterns: ['googletagmanager.com/gtm.js'],
		globalNames: ['google_tag_manager'],
	},
	{
		id: 'ads.pixel.criteo',
		vendor: 'criteo',
		category: 'ad_pixel',
		play: [RETARGET],
		scriptUrlPatterns: ['static.criteo.net', 'criteo.com'],
		globalNames: ['criteo_q'],
	},
	{
		id: 'ads.pixel.trade_desk',
		vendor: 'trade_desk',
		category: 'ad_pixel',
		play: [RETARGET],
		scriptUrlPatterns: ['js.adsrvr.org', 'adsrvr.org'],
		globalNames: ['TTDUniversalPixelApi'],
	},
	{
		id: 'ads.pixel.pinterest',
		vendor: 'pinterest',
		category: 'ad_pixel',
		play: [RETARGET],
		scriptUrlPatterns: ['s.pinimg.com', 'ct.pinterest.com'],
		globalNames: ['pintrk'],
	},
	{
		id: 'ads.pixel.snap',
		vendor: 'snap',
		category: 'ad_pixel',
		play: [RETARGET],
		scriptUrlPatterns: ['sc-static.net', 'tr.snapchat.com'],
		globalNames: ['snaptr'],
	},
	{
		id: 'ads.pixel.bing',
		vendor: 'bing',
		category: 'ad_pixel',
		play: [RETARGET],
		scriptUrlPatterns: ['bat.bing.com'],
		globalNames: ['uetq'],
	},
	{
		id: 'ads.pixel.reddit',
		vendor: 'reddit',
		category: 'ad_pixel',
		play: [RETARGET],
		scriptUrlPatterns: [
			'redditstatic.com/ads',
			'alb.reddit.com',
			'events.reddit.com',
		],
		globalNames: ['rdt'],
	},
	{
		id: 'ads.pixel.amazon',
		vendor: 'amazon',
		category: 'ad_pixel',
		play: [RETARGET],
		scriptUrlPatterns: ['c.amazon-adsystem.com', 'amazon-adsystem.com'],
		globalNames: ['amzn'],
	},
	{
		id: 'ads.pixel.rtb_house',
		vendor: 'rtb_house',
		category: 'ad_pixel',
		play: [RETARGET],
		scriptUrlPatterns: ['creativecdn.com', 'rtbhouse.com'],
		globalNames: [],
	},

	// Recommendations: Order Value Expansion (the PDP surface survives observe-only).
	{
		id: 'recs.recs.nosto',
		vendor: 'nosto',
		category: 'recs',
		play: [OVE],
		scriptUrlPatterns: ['connect.nosto.com', 'nosto.com'],
		globalNames: ['nostojs'],
	},
	{
		id: 'recs.recs.dynamic_yield',
		vendor: 'dynamic_yield',
		category: 'recs',
		play: [OVE],
		scriptUrlPatterns: ['cdn.dynamicyield.com', 'dynamicyield.com'],
		globalNames: ['DY', 'DYO'],
	},
	{
		id: 'recs.recs.rebuy',
		vendor: 'rebuy',
		category: 'recs',
		play: [OVE],
		scriptUrlPatterns: ['cdn.rebuyengine.com', 'rebuyengine.com'],
		globalNames: ['Rebuy'],
	},
	{
		id: 'recs.recs.limespot',
		vendor: 'limespot',
		category: 'recs',
		play: [OVE],
		scriptUrlPatterns: ['api.limespot.com', 'limespot.com'],
		globalNames: ['LimeSpot'],
	},
	{
		id: 'recs.recs.searchspring',
		vendor: 'searchspring',
		category: 'recs',
		play: [OVE],
		scriptUrlPatterns: ['searchspring.net', 'searchspring.io'],
		globalNames: ['SearchSpring'],
	},
	{
		id: 'recs.recs.klevu',
		vendor: 'klevu',
		category: 'recs',
		play: [OVE],
		scriptUrlPatterns: ['js.klevu.com', 'klevu.com'],
		globalNames: ['klevu'],
	},

	// Platform: conditions every rubric; Shopify's server-side Started Checkout is the caveat.
	{
		id: 'platform.shopify',
		vendor: 'shopify',
		category: 'platform',
		play: ALL_PLAYS,
		scriptUrlPatterns: [
			'cdn.shopify.com',
			'myshopify.com',
			'shopifycloud.com',
			'shopify.com/s',
		],
		globalNames: ['Shopify'],
	},
	{
		id: 'platform.bigcommerce',
		vendor: 'bigcommerce',
		category: 'platform',
		play: ALL_PLAYS,
		scriptUrlPatterns: ['bigcommerce.com', 'mybigcommerce.com'],
		globalNames: ['BCData'],
	},
	{
		id: 'platform.salesforce_commerce',
		vendor: 'sfcc',
		category: 'platform',
		play: ALL_PLAYS,
		scriptUrlPatterns: [
			'demandware.static',
			'demandware.edgesuite',
			'dwstatic',
		],
		globalNames: ['dw'],
	},
	{
		id: 'platform.magento',
		vendor: 'magento',
		category: 'platform',
		play: ALL_PLAYS,
		scriptUrlPatterns: ['/static/version', 'mage/cookies', 'magento'],
		globalNames: ['Magento'],
	},
	{
		id: 'platform.woocommerce',
		vendor: 'woocommerce',
		category: 'platform',
		play: ALL_PLAYS,
		scriptUrlPatterns: ['wp-content/plugins/woocommerce', 'woocommerce'],
		globalNames: ['woocommerce_params'],
	},

	// CDP / identity. BlueConic is the hard disqualifier: without this row the tool tells a customer "you're fine".
	{
		id: 'identity.blueconic',
		vendor: 'blueconic',
		category: 'identity',
		play: ALL_PLAYS,
		scriptUrlPatterns: ['blueconic.net', 'blueconic.js', '.blueconic.'],
		globalNames: ['blueConicClient', 'BlueConic'],
	},
	{
		id: 'identity.segment',
		vendor: 'segment',
		category: 'identity',
		play: [PROSPECT, CHURN],
		scriptUrlPatterns: ['cdn.segment.com', 'api.segment.io'],
		globalNames: ['analytics'],
	},
	{
		id: 'identity.mparticle',
		vendor: 'mparticle',
		category: 'identity',
		play: [PROSPECT, CHURN],
		scriptUrlPatterns: ['jssdkcdns.mparticle.com', 'mparticle.com'],
		globalNames: ['mParticle'],
	},
	{
		id: 'identity.tealium',
		vendor: 'tealium',
		category: 'identity',
		play: [PROSPECT, CHURN],
		scriptUrlPatterns: ['tags.tiqcdn.com', 'tealiumiq.com'],
		globalNames: ['utag'],
	},
	{
		id: 'identity.rudderstack',
		vendor: 'rudderstack',
		category: 'identity',
		play: [PROSPECT, CHURN],
		scriptUrlPatterns: ['rudderlabs.com', 'rudderstack.com'],
		globalNames: ['rudderanalytics'],
	},
	{
		id: 'identity.lytics',
		vendor: 'lytics',
		category: 'identity',
		play: [PROSPECT, CHURN],
		scriptUrlPatterns: ['c.lytics.io', 'lytics.io'],
		globalNames: ['jstag'],
	},

	// Loyalty / subscription: free while we're on the page, and the whole input to the Churn/Win-back fast-follow.
	{
		id: 'loyalty.recharge',
		vendor: 'recharge',
		category: 'loyalty',
		play: [CHURN, OVE],
		scriptUrlPatterns: [
			'static.rechargecdn.com',
			'rechargeapps.com',
			'recharge.com',
		],
		globalNames: ['recharge'],
	},
	{
		id: 'loyalty.smile',
		vendor: 'smile',
		category: 'loyalty',
		play: [CHURN],
		scriptUrlPatterns: ['sdk.smile.io', 'smile.io'],
		globalNames: ['SmileUI'],
	},
	{
		id: 'loyalty.loyaltylion',
		vendor: 'loyaltylion',
		category: 'loyalty',
		play: [CHURN],
		scriptUrlPatterns: ['sdk.loyaltylion.net', 'loyaltylion.com'],
		globalNames: ['loyaltylion'],
	},
	{
		id: 'loyalty.yotpo',
		vendor: 'yotpo',
		category: 'loyalty',
		play: [CHURN, OVE],
		scriptUrlPatterns: ['cdn-loyalty.yotpo.com', 'yotpo.com'],
		globalNames: ['yotpo'],
	},
	{
		id: 'loyalty.skio',
		vendor: 'skio',
		category: 'loyalty',
		play: [CHURN],
		scriptUrlPatterns: ['cdn.skio.com', 'skio.com'],
		globalNames: [],
	},
];
